# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Fetch

on:
  schedule:
  - cron: "0 0 * * mon" # https://crontab.guru/#0_0_*_*_mon
  workflow_dispatch:
    # manual run
env:
  KEY: ${{ secrets.HTB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip3 install requests dotenv
    - name: Fetch
      run: |
        python3 runner.py
    - name: Push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -am "Automated update writeups"
        git push
